Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/CyclomaticComplexity:
  IgnoredMethods:
  - fetch
  - cli_arg_version
  - filter_by_fields

Metrics/PerceivedComplexity:
  IgnoredMethods:
  - fetch
  - cli_arg_version
  - filter_by_fields

Metrics/AbcSize:
  CountRepeatedAttributes: false
  IgnoredMethods:
  - fetch
  - filter_by_fields

Style/ModuleFunction:
  EnforcedStyle: extend_self

Style/MutableConstant:
  Enabled: false